// Lists every third-party component shipped in the app with its license: Rust crates from `cargo metadata`,
// npm packages from the production dependency tree. Writes THIRD_PARTY_LICENSES.md.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

// fileURLToPath, not .pathname: on Windows the latter gives "/D:/..." and every command fails to start.
const root = fileURLToPath(new URL("..", import.meta.url));
const rows = [];

const meta = JSON.parse(
  execSync("cargo metadata --format-version 1 --locked", { cwd: join(root, "src-tauri"), maxBuffer: 256 << 20 }).toString(),
);
// Only crates reachable from our package (normal deps), not the whole lockfile.
const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
const seen = new Set();
const walk = (id) => {
  if (seen.has(id)) return;
  seen.add(id);
  for (const d of nodes.get(id)?.deps ?? []) {
    if (d.dep_kinds.some((k) => k.kind === null)) walk(d.pkg);
  }
};
walk(meta.resolve.root);
for (const p of meta.packages) {
  if (!seen.has(p.id) || p.name === "unslouch") continue;
  rows.push({ name: p.name, version: p.version, license: p.license ?? "see repository", url: p.repository ?? "" });
}

const npmTree = JSON.parse(execSync("npm ls --omit=dev --all --json", { cwd: root, maxBuffer: 64 << 20 }).toString());
const npmSeen = new Set();
const npmWalk = (deps = {}) => {
  for (const [name, info] of Object.entries(deps)) {
    const key = `${name}@${info.version}`;
    if (npmSeen.has(key)) continue;
    npmSeen.add(key);
    const pkgPath = join(root, "node_modules", name, "package.json");
    const pkg = existsSync(pkgPath) ? JSON.parse(readFileSync(pkgPath, "utf8")) : {};
    const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url ?? "";
    rows.push({ name, version: info.version, license: pkg.license ?? "see repository", url: repo.replace(/^git\+/, "") });
    npmWalk(info.dependencies);
  }
};
npmWalk(npmTree.dependencies);

rows.sort((a, b) => a.name.localeCompare(b.name));
const md = [
  "# Third-party licenses",
  "",
  "Unslouch is MIT licensed. It is built with these open-source components; each keeps its own license.",
  "Generated by `node scripts/licenses.mjs`.",
  "",
  "| Component | Version | License | Source |",
  "|---|---|---|---|",
  ...rows.map((r) => `| ${r.name} | ${r.version} | ${r.license} | ${r.url} |`),
  "",
].join("\n");
writeFileSync(join(root, "THIRD_PARTY_LICENSES.md"), md);
console.log(`${rows.length} components`);
